name: Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  tests:
    name: PR
    uses: swift-libp2p/github-workflows/.github/workflows/pull_request.yml@main
    with:
      api_breakage_check_enabled: false
      test_in_release_configuration: true
